import { useEffect, useState } from "react";
import { useAuthStore } from "../../state/authStore";
import { fetchAllSettings, updateSetting, invalidateSettingsCache, type DashboardSetting } from "../../services/settingsApi";

const CATEGORY_LABEL: Record<string, string> = { aging: "⏱ Threshold Aging", app: "🏷 Aplikasi", columns: "📋 Nama Kolom GSheet" };
const ALLOWED_ROLES = ["superuser", "engineer"];

export default function DashboardSettings() {
  const { hasRole } = useAuthStore();
  const [settings, setSettings] = useState<DashboardSetting[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editKey, setEditKey] = useState<string | null>(null); const [editValue, setEditValue] = useState(""); const [saving, setSaving] = useState(false); const [saveMsg, setSaveMsg] = useState(""); const [cacheMsg, setCacheMsg] = useState("");
  const allowed = ALLOWED_ROLES.some(r => hasRole(r));
  useEffect(() => { if (!allowed) return; setLoading(true); fetchAllSettings().then(setSettings).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [allowed]);
  if (!allowed) return null;
  const grouped = settings.reduce<Record<string, DashboardSetting[]>>((acc, s) => { (acc[s.category] ??= []).push(s); return acc; }, {});
  const saveEdit = async (key: string) => { setSaving(true); setSaveMsg(""); try { const updated = await updateSetting(key, editValue); setSettings(prev => prev.map(s => s.key === key ? updated : s)); setEditKey(null); setSaveMsg(`'${key}' berhasil disimpan`); setTimeout(() => setSaveMsg(""), 3000); } catch (e: any) { setSaveMsg(e.message); } finally { setSaving(false); } };
  const reloadCache = async () => { setCacheMsg("Memuat ulang cache..."); try { await invalidateSettingsCache(); setCacheMsg("Cache berhasil di-reload"); } catch { setCacheMsg("Gagal reload cache"); } setTimeout(() => setCacheMsg(""), 3000); };
  return <section className="rounded-3xl border overflow-hidden" style={{ background: "var(--bg-surface)", borderColor: "var(--border)" }}>
    <div className="p-4 sm:p-5 border-b flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3" style={{ borderColor: "var(--border)" }}><div><h2 className="text-sm font-bold" style={{ color: "var(--text-primary)" }}>Pengaturan Dashboard</h2><p className="text-xs mt-1" style={{ color: "var(--text-muted)" }}>Konfigurasi threshold, nama aplikasi, dan kolom GSheet.</p></div><div className="flex items-center gap-2"><button onClick={reloadCache} className="rounded-xl px-3 py-2 text-xs font-semibold" style={{ background: "var(--bg-surface2)", color: "var(--text-primary)", border: "1px solid var(--border)" }}>↻ Reload Cache</button>{cacheMsg && <span className="text-xs" style={{ color: "var(--accent)" }}>{cacheMsg}</span>}</div></div>
    <div className="p-4 sm:p-5 space-y-5">{loading && <p className="text-sm" style={{ color: "var(--text-muted)" }}>Memuat settings...</p>}{error && <p className="text-sm text-red-500">{error}</p>}{Object.entries(grouped).map(([category, items]) => <div key={category}><h3 className="text-xs font-bold uppercase tracking-wider mb-2" style={{ color: "var(--text-muted)" }}>{CATEGORY_LABEL[category] ?? category}</h3><div className="rounded-2xl border overflow-hidden" style={{ borderColor: "var(--border)" }}>{items.map(s => <div key={s.key} className="p-3 sm:p-4 flex flex-col sm:flex-row sm:items-center gap-3 border-b last:border-b-0" style={{ borderColor: "var(--border)" }}><div className="min-w-0 flex-1"><p className="text-sm font-medium" style={{ color: "var(--text-primary)" }}>{s.label}</p>{s.description && <p className="text-xs mt-0.5" style={{ color: "var(--text-muted)" }}>{s.description}</p>}<p className="text-[10px] mt-1 font-mono" style={{ color: "var(--text-muted)" }}>{s.key}</p></div><div className="flex items-center gap-2 shrink-0">{editKey === s.key ? <><input className="w-full sm:w-40 rounded-xl px-3 py-2 text-sm outline-none" style={{ background: "var(--input-bg)", border: "1px solid var(--accent)", color: "var(--text-primary)" }} value={editValue} onChange={e => setEditValue(e.target.value)} onKeyDown={e => { if (e.key === "Enter") saveEdit(s.key); if (e.key === "Escape") setEditKey(null); }} autoFocus /><button onClick={() => saveEdit(s.key)} disabled={saving} className="rounded-xl px-3 py-2 text-xs font-bold text-white" style={{ background: "var(--accent)" }}>{saving ? "..." : "Simpan"}</button></> : <><span className="max-w-[220px] truncate rounded-xl px-3 py-2 text-xs font-mono" style={{ background: "var(--bg-surface2)", color: "var(--text-primary)" }}>{s.value}</span>{s.is_editable && <button onClick={() => { setEditKey(s.key); setEditValue(s.value); setSaveMsg(""); }} className="rounded-xl px-2.5 py-2 text-xs" style={{ color: "var(--text-secondary)" }}>✏️</button>}</>}</div></div>)}</div></div>)}</div>
    {!loading && settings.length > 0 && <div className="px-4 sm:px-5 pb-4 text-[11px]" style={{ color: "var(--text-muted)" }}>{saveMsg || `Total ${settings.length} settings.`}</div>}
  </section>;
}
